BINARY:
    # arduino-cli binary download link
    LINK: https://downloads.arduino.cc/arduino-cli/arduino-cli_latest_Linux_ARMv7.tar.gz
    # base dir where /bin/arduino-cli will be installed
    BASE: /home/pi/bin
    CORES: # links for board cores you want to install 
        LINKS: # these will be appended in arduino-cli's config file
            - http://drazzy.com/package_drazzy.com_index.json
            - https://dl.espressif.com/dl/package_esp32_index.json
        CORE_NAMES: # names of cores you want to install. Note that I have used full FQBN here
            - megaTinyCore:megaavr 
            - esp32:esp32

LIBS: # 3rd-party libraries you want to install (can be both names or git links)
    - https://github.com/dattasaurabh82/TinyMegaI2CMaster.git
    - TinyMegaI2C
    - RV8803Tiny

FIRMWARE: 
    # firmware/s, that needs to be cloned goes here
    LINKS:
        - https://github.com/dattasaurabh82/clock_firmware_production.git